name: Databricks Notebook CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@v0.216.0
        with:
          databricks-host: ${{ secrets.DATABRICKS_HOST }}
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Import notebooks to Databricks workspace
        run: databricks workspace import_dir ./notebooks /Users/rufinadcosta@gmail.com/FlightDelay
